### ISSUE TITLE
Unable to link to libtensorflow_cc.so

### ISSUE THREAD

**Issue by serenagomez1304** [mlcommons/inference_results_v1.0#3]
I'm following the instructions in _"Instructions for building TensorFlow and MLPerf loadgen integration"_ posted here: 
https://github.com/mlcommons/inference_results_v1.0/tree/master/closed/Intel/code/resnet50/tensorflow

During the _"Build Tensorflow Backend"_ phase, while running the Makefile in loadrun I was encountered with the following error:

```
$ g++ -fopenmp loadrun.cc -O3 -fpic -Wall -std=gnu++14 -g -I/usr/include -I/home/serena/loadgen -I/home/serena/deps-installations2/tf-cc/include -I/usr/include/opencv4 -L/usr/lib -L/home/serena/loadgen/build -L/home/serena/deps-installations2/tf-cc/lib -L/usr/lib -L/home/serena/sf_Intel/code/resnet50/tensorflow/loadrun/../backend -o loadrun -lpthread -lrt -lmlperf_loadgen -ltensorflow_cc -ltensorflow_backend -lboost_filesystem -lboost_system -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs
/usr/bin/ld: cannot find -ltensorflow_cc
collect2: error: ld returned 1 exit status
make: *** [Makefile:20: loadrun] Error 1
```

I have built libtensorflow_cc.so locally; and placed it in the LDFLAGS path(/home/serena/depsinstallations2/tf-cc/lib).
However, I get the above error. Any help or pointers.
```
$ ls -al
total 828456
drwxrwxr-x 2 serena serena      4096 Jun 27 16:41 .
drwxrwxr-x 4 serena serena      4096 Jun 29 18:04 ..
-rwxr-xr-x 1 serena serena   2226679 Jun  9 10:18 libiomp5.so
-rwxr-xr-x 1 serena serena 130121414 Jun  9 10:18 libmklml_intel.so
lrwxrwxrwx 1 serena serena        29 Jun 27 16:41 libtensorflow_cc.so -> ./lib/libtensorflow_cc.so.2.0
lrwxrwxrwx 1 serena serena        31 Jun 27 16:41 libtensorflow_cc.so.2 -> ./lib/libtensorflow_cc.so.2.5.0
-r-xr-xr-x 1 serena serena 391381888 Jun 27 16:39 libtensorflow_cc.so.2.5.0
-r-xr-xr-x 1 serena serena 324587936 Jun 20 12:03 libtensorflow.so
```

**Comment by serenagomez1304** [comment]
for future reference, I did the following:
* copied `libtensorflow_cc.so.2.5.0` from `deps-installations/tf-cc/lib` to `usr/local/lib`; soft-linked `libtensorflow_cc.so` to `libtensorflow_cc.so.2.5.0`
* copied `libtensorflow_backend.a` from `inference_results_v1.0/closed/Intel/code/resnet50/tensorflow/backend` to `usr/local/lib`

Then I ran the  Makfile in [loadrun](https://github.com/mlcommons/inference_results_v1.0/tree/master/closed/Intel/code/resnet50/tensorflow/loadrun) under "Build Tensorflow Backend" and I was able to proceed to the next steps.

**Comment by fenz** [comment]
@serenagomez1304 I have similar issues trying to reproduce the environment for this submission. In the guide it is used TensorFlow 2.3 while you used the version 2.5, it is the only thing you changes? What the command you used to build TensorFlow?
I'm having hard times trying to build using GCC 10 (as from the guide), every build/try takes hours and it would be good to know more info about working build steps.

**Comment by fenz** [comment]
I just saw you opened this: https://github.com/mlcommons/inference_results_v1.0/issues/10#issue-986783441 as well and that's exactly the error I have so I'll comment there.
