### ISSUE TITLE
[TensorRT] INTERNAL ERROR: Assertion failed: status==STATUS_SUCCESS

### ISSUE THREAD

**Issue by TianningWang** [mlcommons/inference_results_v1.0#4]
Code dir: closed/NVIDIA
Test benchmark: ssd-resnet34
Scenarios: Server
When I running command
`make run RUN_ARGS="--benchmarks=ssd-resnet34 --scenarios=Server --test_mode=PerformanceOnly"`
and
`make run RUN_ARGS="--benchmarks=ssd-resnet34 --scenarios=Server --config_ver=triton --test_mode=PerformanceOnly"`
there all have this kind of error
```
[2021-07-01 10:26:57,901 builder.py:149 INFO] Building ./build/engines/Tesla P4x1/ssd-resnet34/Server/ssd-resnet34-Server-gpu-b2-int8.default.plan
[TensorRT] WARNING: Calibration Profile is not defined. Runing calibration with Profile 0
[TensorRT] INFO: Detected 1 inputs and 1 output network tensors.
[TensorRT] INFO: Starting Calibration.
Calibrating with batch 0
[TensorRT] INTERNAL ERROR: Assertion failed: status == STATUS_SUCCESS
/work/code/plugin/NMSOptPlugin/src/nmsPluginOpt.cpp:183
Aborting...

Traceback (most recent call last):
  File "code/main.py", line 703, in <module>
    main(main_args, system)
  File "code/main.py", line 634, in main
    launch_handle_generate_engine(*_gen_args, **_gen_kwargs)
  File "code/main.py", line 62, in launch_handle_generate_engine
    raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
Makefile:606: recipe for target 'generate_engines' failed
make[1]: *** [generate_engines] Error 1
make[1]: Leaving directory '/work'
Makefile:600: recipe for target 'run' failed
make: *** [run] Error 2
```
I have built test docker successfully by running command
`make prebuild`
and already built the required libraries and TensorRT plugins successfully by running command
`make build`
my gpu is tesla p4, and here is my config file
code/common/system_list.py
`P4=SystemClass("Tesla P4",["Tesla P4"],["1BB3"],Architecture.Unknow,[1])`
configs/ssd-resnet34/Server/config.json
```
"Tesla P4": {
        "config_ver": {
            "triton": {
                "instance_group_count": 4,
                "server_target_qps": 110,
                "use_triton": true
            }
        },
        "deque_timeout_usec": 2000,
        "gpu_batch_size": 2,
        "gpu_inference_streams": 4,
        "server_target_qps": 110,
        "use_cuda_thread_per_device": false
    },
```
So where the problem is? Is there something wrong with config file, inference data or model?

**Comment by jqueguiner** [comment]
You need to generate you harness before.

**Comment by jqueguiner** [comment]
make generate_engines RUN_ARGS="--benchmarks=<BENCHMARKS> --scenarios=<SCENARIOS> --config_ver=default,high_accuracy [OTHER FLAGS]"

**Comment by jqueguiner** [comment]
Oups I saw it's a P4... si good luck you won't be able to do anything with this. In my experience only Tessa and ampere can be reproduced with nVidia benchmark cause it's used mixed core like int8 or fp16. I don't think p4 has FP16 or int8 or so and won't support this.

I remember going into triton code to have the IF statement changed for the GPU family and Only ampere/Turing KSM were supported.

**Comment by jqueguiner** [comment]
Here it is an exemple of why it won't work

https://github.com/NVIDIA/TensorRT/blob/eb5de99b523c76c2f3ae997855ad86d3a1e86a31/plugin/bertQKVToContextPlugin/qkvToContextInt8InterleavedPlugin.cpp#L65

**Comment by TianningWang** [comment]
> Here it is an exemple of why it won't work
> 
> https://github.com/NVIDIA/TensorRT/blob/eb5de99b523c76c2f3ae997855ad86d3a1e86a31/plugin/bertQKVToContextPlugin/qkvToContextInt8InterleavedPlugin.cpp#L65

Thanks for your reply! Now I know why P4 doesn't work. I changed my gpu from a P4 to a T4 and then I was able to run the code properly.
